from pysh.pype.statements.statement import Statement
from pysh.pype.statements.result import Result
from pysh.pype.statements.assignment import Assignment
from pysh.pype.statements.block import Block
from pysh.pype.statements.class_ import Class
from pysh.pype.statements.empty import Empty
from pysh.pype.statements.expr_statement import ExprStatement
from pysh.pype.statements.func import Func
from pysh.pype.statements.return_ import Return
